spring.application.name=Bknd_User
server.port=${PORT:8081}

# PostgreSQL Render
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

# Mostrar errores
spring.web.error.include-stacktrace=always
spring.web.error.include-message=always

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Google Sign-In
google.client-id=${GOOGLE_CLIENT_ID:}

# Email Configuration - Resend API
resend.api.key=${RESEND_API_KEY}
resend.from.email=${RESEND_FROM_EMAIL:noreply@monex.app}

# Swagger/SpringDoc OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.filter=true

# URLs microservicios desplegados en Render
expenses.service.url=https://expenses-service-x5hz.onrender.com
categories.service.url=https://categories-service-75op.onrender.com